export { validAnswers, validAbbreviations, abbreviationsObjects };

const validAnswers = [
  { abbreviation: 'ACT', definition: 'Airway clearance technique' },
  { abbreviation: 'BGL', definition: 'Blood glucose level' },
  { abbreviation: 'ADHD', definition: 'Attention deficit hyperactivity disorder' },
  { abbreviation: 'COLD', definition: 'Chronic obstructive lung disease' },
  { abbreviation: 'DEXA', definition: 'Dual energy x-ray absortiometry' },
  { abbreviation: 'EUA', definition: 'Examination under anaesthetic' }
]

const validAbbreviations = [
  "AAA",
  "AACG",
  "ABC",
  "ABG",
  "ABI",
  "ABO",
  "ABPA",
  "ABPI",
  "ACBT",
  "ACH",
  "ACJ",
  "ACL",
  "ACS",
  "ACT",
  "ADEM",
  "ADH",
  "ADHD",
  "ADL",
  "AEDF",
  "AET",
  "AFO",
  "AFR",
  "AFV",
  "AGA",
  "AIDS",
  "AIIS",
  "AKA",
  "AKI",
  "ALIF",
  "ALL",
  "ALR",
  "ALT",
  "AMI",
  "AML",
  "AMP",
  "ANA",
  "AND",
  "ANP",
  "APD",
  "APH",
  "APRS",
  "APTT",
  "ARDS",
  "ARF",
  "ARM",
  "ARMD",
  "AROM",
  "ASA",
  "ASD",
  "ASIS",
  "ASL",
  "ASR",
  "AST",
  "ATNR",
  "AUC",
  "AVA",
  "AVB",
  "AVM",
  "AVR",
  "AVSD",
  "BAWO",
  "BBA",
  "BBB",
  "BBS",
  "BC",
  "BCG",
  "BCL",
  "BEE",
  "BGL",
  "BHCG",
  "BHT",
  "BHX",
  "BIA",
  "BKA",
  "BLS",
  "BMA",
  "BMI",
  "BMR",
  "BMT",
  "BNA",
  "BNO",
  "BOS",
  "BPD",
  "BPM",
  "BPP",
  "BSA",
  "BSO",
  "BSS",
  "BTL",
  "BUN",
  "BUPA",
  "CABG",
  "CAD",
  "CANC",
  "CAPD",
  "CAVD",
  "CBC",
  "CBD",
  "CBG",
  "CBT",
  "CCF",
  "CCPD",
  "CCT",
  "CCU",
  "CDAD",
  "CEA",
  "CEO",
  "CFAM",
  "CFM",
  "CGA",
  "CHB",
  "CHD",
  "CHO",
  "CIN",
  "CJD",
  "CKMB",
  "CLD",
  "CLL",
  "CLO",
  "CMCJ",
  "CML",
  "CMP",
  "CMV",
  "CNS",
  "COA",
  "COD",
  "COLD",
  "COPD",
  "CORS",
  "CPAP",
  "CPC",
  "CPD",
  "CPK",
  "CPM",
  "CPR",
  "CRC",
  "CRF",
  "CRP",
  "CRRT",
  "CSE",
  "CSF",
  "CSII",
  "CSOM",
  "CSU",
  "CTA",
  "CTEV",
  "CTG",
  "CTR",
  "CTS",
  "CTSS",
  "CVA",
  "CVAD",
  "CVC",
  "CVL",
  "CVP",
  "CVS",
  "CVVH",
  "CWMS",
  "CWO",
  "CXR",
  "DBE",
  "DCIS",
  "DCR",
  "DDH",
  "DEXA",
  "DHS",
  "DIC",
  "DILV",
  "DIPJ",
  "DNA",
  "DOA",
  "DOB",
  "DOE",
  "DORV",
  "DOSS",
  "DPM",
  "DPNS",
  "DSH",
  "DVT",
  "EAC",
  "EBL",
  "EBM",
  "ECG",
  "ECHO",
  "ECLS",
  "ECMO",
  "ECT",
  "ECV",
  "EDD",
  "EEG",
  "EER",
  "EFA",
  "EFM",
  "EFW",
  "EGA",
  "EHL",
  "EMG",
  "EMS",
  "EMU",
  "ENT",
  "EOM",
  "EOR",
  "EPAU",
  "EPL",
  "EPS",
  "ERCP",
  "ERPC",
  "ESKD",
  "ESR",
  "EST",
  "ESWL",
  "EUA",
  "EUM",
  "EVAR",
  "EVLT",
  "FAD",
  "FAS",
  "FBC",
  "FBM",
  "FBS",
  "FDP",
  "FDS",
  "FEES",
  "FES",
  "FESS",
  "FET",
  "FFD",
  "FFP",
  "FHH",
  "FHHR",
  "FHNH",
  "FHR",
  "FLP",
  "FMF",
  "FNA",
  "FNAB",
  "FOB",
  "FROM",
  "FSE",
  "FSH",
  "FTA",
  "FTND",
  "FTT",
  "FVC",
  "FWB",
  "GBS",
  "GCS",
  "GCSF",
  "GCT",
  "GDM",
  "GFR",
  "GHJ",
  "GIT",
  "GORD",
  "GTN",
  "GTT",
  "GUM",
  "GUR",
  "GVHD",
  "GXM",
  "GZF",
  "HAV",
  "HBB",
  "HBH",
  "HBV",
  "HCA",
  "HCG",
  "HCV",
  "HDL",
  "HDU",
  "HEP",
  "HFOV",
  "HIE",
  "HIPE",
  "HIT",
  "HITS",
  "HIV",
  "HLA",
  "HMD",
  "HPHC",
  "HPOA",
  "HRT",
  "HSE",
  "HSP",
  "HTN",
  "HUS",
  "HVS",
  "IABP",
  "IAS",
  "IBW",
  "ICP",
  "ICU",
  "IDPN",
  "IDWG",
  "IFT",
  "IHD",
  "IHF",
  "IMB",
  "IMV",
  "INR",
  "IOL",
  "IOP",
  "IPD",
  "IPJ",
  "IPPB",
  "IPPV",
  "IRQ",
  "ISC",
  "ISQ",
  "ITP",
  "ITT",
  "ITU",
  "IUCD",
  "IUD",
  "IUGR",
  "IVC",
  "IVDU",
  "IVF",
  "IVH",
  "IVI",
  "IVP",
  "IVS",
  "IVSD",
  "IVSS",
  "IVT",
  "IVU",
  "IVUS",
  "IWA",
  "JIA",
  "JVP",
  "KAFO",
  "KCL",
  "KUB",
  "KVO",
  "LAA",
  "LADA",
  "LAVH",
  "LBBB",
  "LBM",
  "LBP",
  "LCL",
  "LCT",
  "LCX",
  "LDH",
  "LDL",
  "LGA",
  "LHS",
  "LIF",
  "LIH",
  "LLQ",
  "LMA",
  "LMP",
  "LOA",
  "LOC",
  "LOL",
  "LOP",
  "LOR",
  "LRTI",
  "LSA",
  "LSCS",
  "LSF",
  "LSH",
  "LSL",
  "LSO",
  "LSP",
  "LTM",
  "LTM",
  "LTS",
  "LUQ",
  "LUS",
  "LVAD",
  "LVDV",
  "LVF",
  "LVH",
  "LVOT",
  "LVS",
  "LVSV",
  "MAP",
  "MAS",
  "MAU",
  "MCA",
  "MCL",
  "MCPJ",
  "MCUG",
  "MCV",
  "MDA",
  "MDT",
  "MDU",
  "MFR",
  "MLB",
  "MMK",
  "MMR",
  "MMSE",
  "MNB",
  "MND",
  "MPT",
  "MRCP",
  "MRI",
  "MROP",
  "MRSA",
  "MSSA",
  "MSU",
  "MSW",
  "MTPJ",
  "MUA",
  "MUFA",
  "MUGA",
  "MVA",
  "MVR",
  "MWM",
  "NAD",
  "NAG",
  "NAI",
  "NAS",
  "NBFD",
  "NCA",
  "NCHD",
  "NEC",
  "NETZ",
  "NFA",
  "NFR",
  "NHL",
  "NIBP",
  "NICU",
  "NIEL",
  "NIV",
  "NKA",
  "NKDA",
  "NMS",
  "NND",
  "NOF",
  "NOK",
  "NPL",
  "NPO",
  "NPU",
  "NSR",
  "NTD",
  "NTT",
  "NWB",
  "OCP",
  "OCPD",
  "OFC",
  "OGD",
  "OGTT",
  "OHA",
  "OHSS",
  "OPD",
  "OPE",
  "ORIF",
  "ORQ",
  "PAC",
  "PADL",
  "PAF",
  "PASP",
  "PCA",
  "PCEA",
  "PCI",
  "PCL",
  "PCR",
  "PCV",
  "PDA",
  "PDPH",
  "PEA",
  "PEEP",
  "PEFR",
  "PEG",
  "PEJ",
  "PEM",
  "PERT",
  "PFA",
  "PFJ",
  "PFO",
  "PFR",
  "PGE",
  "PHN",
  "PHT",
  "PICC",
  "PICU",
  "PID",
  "PIH",
  "PIIS",
  "PIP",
  "PIPJ",
  "PKB",
  "PKU",
  "PLAD",
  "PLIF",
  "PLO",
  "PLTS",
  "PMB",
  "PND",
  "PNF",
  "POA",
  "POD",
  "POP",
  "PPH",
  "PPHN",
  "PPN",
  "PPV",
  "PROM",
  "PRP",
  "PSA",
  "PSIS",
  "PSV",
  "PSW",
  "PSWD",
  "PTA",
  "PTB",
  "PTCA",
  "PTSD",
  "PTT",
  "PTTK",
  "PUD",
  "PUFA",
  "PUJ",
  "PUO",
  "PVC",
  "PVD",
  "PVL",
  "PWB",
  "PWD",
  "PWS",
  "QRS",
  "RBBB",
  "RBC",
  "RBG",
  "RCA",
  "RCC",
  "RCJ",
  "RCN",
  "RDS",
  "REE",
  "REM",
  "RFA",
  "RGN",
  "RHS",
  "RICE",
  "RIF",
  "RIG",
  "RIH",
  "RIP",
  "RLQ",
  "RNI",
  "RNID",
  "RNP",
  "RNT",
  "ROA",
  "ROL",
  "ROM",
  "ROP",
  "ROS",
  "RPN",
  "RRT",
  "RSA",
  "RSD",
  "RSF",
  "RSI",
  "RSO",
  "RSP",
  "RSV",
  "RTA",
  "RTI",
  "RTS",
  "RTW",
  "RUJ",
  "RUQ",
  "RVDV",
  "RVF",
  "RVH",
  "RVOT",
  "RVSP",
  "RVSV",
  "RZF",
  "SAD",
  "SAH",
  "SARS",
  "SBA",
  "SBBE",
  "SBE",
  "SBFT",
  "SBR",
  "SCBU",
  "SCC",
  "SCD",
  "SCJ",
  "SFA",
  "SFD",
  "SGA",
  "SHO",
  "SIC",
  "SIDS",
  "SIJ",
  "SIMV",
  "SLE",
  "SLR",
  "SLT",
  "SMD",
  "SMR",
  "SNAG",
  "SOB",
  "SOP",
  "SRF",
  "SROM",
  "SSD",
  "SSG",
  "SSM",
  "SSN",
  "SSPE",
  "STAH",
  "STAR",
  "STI",
  "STJ",
  "STM",
  "STNR",
  "STR",
  "SUI",
  "SVC",
  "SVCO",
  "SVD",
  "SVRA",
  "SVT",
  "SWD",
  "TAH",
  "TAR",
  "TBC",
  "TBI",
  "TBG",
  "TBL",
  "TBW",
  "TCM",
  "TCOM",
  "TCRE",
  "TEE",
  "TENS",
  "TEP",
  "TER",
  "TES",
  "TFA",
  "TFVT",
  "TGA",
  "THR",
  "TIA",
  "TIBC",
  "TICH",
  "TKR",
  "TMD",
  "TMJ",
  "TMP",
  "TOE",
  "TOF",
  "TOP",
  "TPHA",
  "TPN",
  "TPR",
  "TRH",
  "TSH",
  "TSR",
  "TTN",
  "TTWB",
  "TUAG",
  "TURB",
  "TVI",
  "TVS",
  "UAC",
  "UBW",
  "ULTT",
  "UPPP",
  "URTI",
  "USS",
  "UST",
  "UTI",
  "UVC",
  "UVJ",
  "UWSD",
  "VAS",
  "VBAC",
  "VBG",
  "VCJD",
  "VDRL",
  "VFU",
  "VHI",
  "VIN",
  "VLCD",
  "VMA",
  "VML",
  "VMO",
  "VRE",
  "VSB",
  "VSD",
  "VVF",
  "VZIG",
  "WBC",
  "WCC",
  "WFD",
  "WFL",
  "WNL",
  "WPWS",
  "WZF"
]

const abbreviationsObjects = [
  { abbreviation: 'AAA', definition: 'Abdominal aortic aneurysm' },
  { abbreviation: 'AACG', definition: 'Acute angle closure glaucoma' },
  { abbreviation: 'ABC', definition: 'Airway breathing circulation' },
  { abbreviation: 'ABG', definition: 'Arterial blood gas' },
  { abbreviation: 'ABI', definition: 'Ankle brachial index' },
  { abbreviation: 'ABO', definition: 'Blood group system' },
  { abbreviation: 'ABPA', definition: 'Allergic broncho pulmonary aspergillosis' },
  { abbreviation: 'ABPI', definition: 'Ankle brachial pulse index' },
  { abbreviation: 'ACBT', definition: 'Active cycle of breathing technique' },
  { abbreviation: 'ACH', definition: 'After coming head' },
  { abbreviation: 'ACJ', definition: 'Acromioclavicular joint' },
  { abbreviation: 'ACL', definition: 'Anterior cruciate ligament' },
  { abbreviation: 'ACS', definition: 'Acute coronary syndrome' },
  { abbreviation: 'ACT', definition: 'Airway clearance technique' },
  { abbreviation: 'ADEM', definition: 'Acute disseminated encephalomyelitis' },
  { abbreviation: 'ADH', definition: 'Antidiuretic hormone' },
  { abbreviation: 'ADHD', definition: 'Attention deficit hyperactivity disorder' },
  { abbreviation: 'ADL', definition: 'Activities of daily living' },
  { abbreviation: 'AEDF', definition: 'Absent end diastolic flow' },
  { abbreviation: 'AET', definition: 'Atrial ectopic tachycardia' },
  { abbreviation: 'AFO', definition: 'Ankle foot orthosis' },
  { abbreviation: 'AFR', definition: 'Average flow rate' },
  { abbreviation: 'AFV', definition: 'Amniotic fluid volume' },
  { abbreviation: 'AGA', definition: 'Appropriate gestational age' },
  { abbreviation: 'AIDS', definition: 'Acquired immune deficiency syndrome' },
  { abbreviation: 'AIIS', definition: 'Anterior inferior iliac spine' },
  { abbreviation: 'AKA', definition: 'Above knee amputation' },
  { abbreviation: 'AKI', definition: 'Acute kidney injury' },
  { abbreviation: 'ALIF', definition: 'Anterior lumbar intervertebral fusion' },
  { abbreviation: 'ALL', definition: 'Acute lymphoblastic leukaemia' },
  { abbreviation: 'ALR', definition: 'Anterior levator resection' },
  { abbreviation: 'ALT', definition: 'Alanine amino transferase' },
  { abbreviation: 'AMI', definition: 'Acute myocardial infarction' },
  { abbreviation: 'AML', definition: 'Acute myeloid leukaemia' },
  { abbreviation: 'AMP', definition: 'Advanced Midwife Practitioner' },
  { abbreviation: 'ANA', definition: 'Antinuclear Antibody' },
  { abbreviation: 'AND', definition: 'Adverse neural dynamics' },
  { abbreviation: 'ANP', definition: 'Advanced Nurse Practitioner' },
  { abbreviation: 'APD', definition: 'Automated peritoneal dialysis' },
  { abbreviation: 'APH', definition: 'Ante partum haemorrhage' },
  { abbreviation: 'APRS', definition: 'Aspiration-penetration rating scale' },
  { abbreviation: 'APTT', definition: 'Activated partial thromboplastin time' },
  { abbreviation: 'ARDS', definition: 'Acute Respiratory Distress Syndrome' },
  { abbreviation: 'ARF', definition: 'Acute renal failure' },
  { abbreviation: 'ARM', definition: 'Artificial rupture of membranes' },
  { abbreviation: 'ARMD', definition: 'Age related macular degeneration' },
  { abbreviation: 'AROM', definition: 'Active range of movement/motion' },
  { abbreviation: 'ASA', definition: 'American Society of Anaesthesiologists' },
  { abbreviation: 'ASD', definition: 'Atrial septal defect' },
  { abbreviation: 'ASIS', definition: 'Anterior superior iliac spine' },
  { abbreviation: 'ASL', definition: 'Alternate side-lying' },
  { abbreviation: 'ASR', definition: 'Articular surface replacement' },
  { abbreviation: 'AST', definition: 'Aspartate amino transferase' },
  { abbreviation: 'ATNR', definition: 'Assymetric tonic neck reflex' },
  { abbreviation: 'AUC', definition: 'Area under the curve' },
  { abbreviation: 'AVA', definition: 'Aortic valve area' },
  { abbreviation: 'AVB', definition: 'Atrioventricular block' },
  { abbreviation: 'AVM', definition: 'Arteriovenous malformation' },
  { abbreviation: 'AVR', definition: 'Aortic valve replacement' },
  { abbreviation: 'AVSD', definition: 'Atrioventricular septal defect' },
  { abbreviation: 'BAWO', definition: 'Bilateral antral washout' },
  { abbreviation: 'BBA', definition: 'Born before admission/arrival' },
  { abbreviation: 'BBB', definition: 'Bundle branch block' },
  { abbreviation: 'BBS', definition: 'Berg balance scale' },
  { abbreviation: 'BC', definition: 'Blood cultures' },
  { abbreviation: 'BCG', definition: 'Bacille Calmette-guerin' },
  { abbreviation: 'BCL', definition: 'Bandage contact lens' },
  { abbreviation: 'BEE', definition: 'Basal energy expenditure' },
  { abbreviation: 'BGL', definition: 'Blood glucose level' },
  { abbreviation: 'BHCG', definition: 'Beta human chorionic gonadotropins' },
  { abbreviation: 'BHT', definition: 'Bucket handle tear' },
  { abbreviation: 'BHX', definition: 'Birth history' },
  { abbreviation: 'BIA', definition: 'Bioelectrical impedance analyzer' },
  { abbreviation: 'BKA', definition: 'Below knee amputation' },
  { abbreviation: 'BLS', definition: 'Basic life support' },
  { abbreviation: 'BMA', definition: 'Bone marrow aspirate' },
  { abbreviation: 'BMI', definition: 'Body mass index' },
  { abbreviation: 'BMR', definition: 'Basal metabolic rate' },
  { abbreviation: 'BMT', definition: 'Bone marrow transplant' },
  { abbreviation: 'BNA', definition: 'Borderline nuclear abnormality' },
  { abbreviation: 'BNO', definition: 'Bowels not open' },
  { abbreviation: 'BOS', definition: 'Base of support' },
  { abbreviation: 'BPD', definition: 'Biparietal diameter' },
  { abbreviation: 'BPM', definition: 'Beats per minute' },
  { abbreviation: 'BPP', definition: 'Bio-physical profile' },
  { abbreviation: 'BSA', definition: 'Body surface area' },
  { abbreviation: 'BSO', definition: 'Bilateral salpingo- oophorectomy' },
  { abbreviation: 'BSS', definition: 'Blood sugar series' },
  { abbreviation: 'BTL', definition: 'Bilateral tubal ligation' },
  { abbreviation: 'BUN', definition: 'Blood urea nitrogen' },
  { abbreviation: 'BUPA', definition: 'British united Provident Association' },
  { abbreviation: 'CABG', definition: 'Coronary artery bypass graft' },
  { abbreviation: 'CAD', definition: 'Coronary artery disease' },
  { abbreviation: 'CANC', definition: 'Combined Antenatal care' },
  { abbreviation: 'CAPD', definition: 'Continuous ambulatory peritoneal dialysis' },
  { abbreviation: 'CAVD', definition: 'Complete atrioventricular block' },
  { abbreviation: 'CBC', definition: 'Capillary blood count' },
  { abbreviation: 'CBD', definition: 'Common bile duct' },
  { abbreviation: 'CBG', definition: 'Capillary blood gases' },
  { abbreviation: 'CBT', definition: 'Cognitive behaviour therapy' },
  { abbreviation: 'CCF', definition: 'Congestive cardiac failure' },
  { abbreviation: 'CCPD', definition: 'Continuous cycling peritoneal dialysis' },
  { abbreviation: 'CCT', definition: 'Controlled cord traction' },
  { abbreviation: 'CCU', definition: 'Coronary Care unit' },
  { abbreviation: 'CDAD', definition: 'Clostridium difficile associated disease' },
  { abbreviation: 'CEA', definition: 'Carotid endarterectomy' },
  { abbreviation: 'CEO', definition: 'Chief Executive Officer' },
  { abbreviation: 'CFAM', definition: 'Cerebral function amplitude' },
  { abbreviation: 'CFM', definition: 'Cerebral function monitoring' },
  { abbreviation: 'CGA', definition: 'Contact guard assistance' },
  { abbreviation: 'CHB', definition: 'Complete heart block' },
  { abbreviation: 'CHD', definition: 'Coronary heart disease' },
  { abbreviation: 'CHO', definition: 'Carbohydrate' },
  { abbreviation: 'CIN', definition: 'Cervical intraepithelial neoplasia' },
  { abbreviation: 'CJD', definition: 'Creutzfeldt-Jakob Disease' },
  { abbreviation: 'CKMB', definition: 'Creatine kinase isoenzyme' },
  { abbreviation: 'CLD', definition: 'Chronic lung disease' },
  { abbreviation: 'CLL', definition: 'Chronic lymphocytic leukaemia' },
  { abbreviation: 'CLO', definition: 'Campbylobacter like organism' },
  { abbreviation: 'CMCJ', definition: 'Carpal metacarpal joint' },
  { abbreviation: 'CML', definition: 'Chronic myeloid leukaemia' },
  { abbreviation: 'CMP', definition: 'Chondromalacia pattellae' },
  { abbreviation: 'CMV', definition: 'Cytomegalovirus' },
  { abbreviation: 'CNS', definition: 'Central nervous system' },
  { abbreviation: 'COA', definition: 'Coarctation of the Aorta' },
  { abbreviation: 'COD', definition: 'Change of dressing' },
  { abbreviation: 'COLD', definition: 'Chronic obstructive lung disease' },
  { abbreviation: 'COPD', definition: 'Chronic obstructive pulmonary disease' },
  { abbreviation: 'CORS', definition: 'Coronary Angiogram' },
  { abbreviation: 'CPAP', definition: 'Continuous positive airway pressure' },
  { abbreviation: 'CPC', definition: 'Clinical Placement Co-Ordinator' },
  { abbreviation: 'CPD', definition: 'Cephalic pelvic disproportion' },
  { abbreviation: 'CPK', definition: 'Creatine phosphokinase' },
  { abbreviation: 'CPM', definition: 'Continuous passive movement' },
  { abbreviation: 'CPR', definition: 'Cardiopulmonary resuscitation' },
  { abbreviation: 'CRC', definition: 'Central Remedial Clinic' },
  { abbreviation: 'CRF', definition: 'Chronic renal failure' },
  { abbreviation: 'CRP', definition: 'C-Reactive protein' },
  { abbreviation: 'CRRT', definition: 'Continuous renal replacement therapy' },
  { abbreviation: 'CSE', definition: 'Combined spinal epidural' },
  { abbreviation: 'CSF', definition: 'Cerebrospinal fluid' },
  { abbreviation: 'CSII', definition: 'Continuous subcutaneous insulin infusion' },
  { abbreviation: 'CSOM', definition: 'Chronic suppurative otitis media' },
  { abbreviation: 'CSU', definition: 'Catheter specimen of urine' },
  { abbreviation: 'CTA', definition: 'Clear to auscultation' },
  { abbreviation: 'CTEV', definition: 'Congenital talipes equina varus' },
  { abbreviation: 'CTG', definition: 'Cardiotocograph' },
  { abbreviation: 'CTR', definition: 'Carpel tunnel release' },
  { abbreviation: 'CTS', definition: 'Carpal tunnel syndrome' },
  { abbreviation: 'CTSS', definition: 'Closed tracheal suction system' },
  { abbreviation: 'CVA', definition: 'Cerebrovascular accident' },
  { abbreviation: 'CVAD', definition: 'Central venous access device' },
  { abbreviation: 'CVC', definition: 'Central venous catheter' },
  { abbreviation: 'CVL', definition: 'Central venous line' },
  { abbreviation: 'CVP', definition: 'Central venous pressure' },
  { abbreviation: 'CVS', definition: 'Cardiovascular system' },
  { abbreviation: 'CVVH', definition: 'Continuous veno-venous haemofiltration' },
  { abbreviation: 'CWMS', definition: 'Colour, warmth, movement, sensation' },
  { abbreviation: 'CWO', definition: 'Community Welfare Officer' },
  { abbreviation: 'CXR', definition: 'Chest x-Ray' },
  { abbreviation: 'DBE', definition: 'Deep breathing exercises' },
  { abbreviation: 'DCIS', definition: 'Ductal carcinoma in situ' },
  { abbreviation: 'DCR', definition: 'Dacryocystorhinostomy' },
  { abbreviation: 'DDH', definition: 'Developmental dysplasia of the hip' },
  { abbreviation: 'DEXA', definition: 'Dual energy x-ray absortiometry' },
  { abbreviation: 'DHS', definition: 'Dynamic hip screw' },
  { abbreviation: 'DIC', definition: 'Disseminated intravascular coagulation' },
  { abbreviation: 'DILV', definition: 'Double inlet left ventricle' },
  { abbreviation: 'DIPJ', definition: 'Distal interphalangeal joint' },
  { abbreviation: 'DNA', definition: 'Did not attend' },
  { abbreviation: 'DOA', definition: 'Dead on arrival' },
  { abbreviation: 'DOB', definition: 'Date of birth' },
  { abbreviation: 'DOE', definition: 'Dyspnoea on exertion' },
  { abbreviation: 'DORV', definition: 'Double outlet right ventricle' },
  { abbreviation: 'DOSS', definition: 'Dysphagia outcome severity scale' },
  { abbreviation: 'DPM', definition: 'Drops per minute' },
  { abbreviation: 'DPNS', definition: 'Deep pharyngeal neuromuscular stimulation' },
  { abbreviation: 'DSH', definition: 'Deliberate self harm' },
  { abbreviation: 'DVT', definition: 'Deep vein thrombosis' },
  { abbreviation: 'EAC', definition: 'External auditory canal' },
  { abbreviation: 'EBL', definition: 'Estimated blood loss' },
  { abbreviation: 'EBM', definition: 'Expressed breast milk' },
  { abbreviation: 'ECG', definition: 'Electrocardiogram' },
  { abbreviation: 'ECHO', definition: 'Echocardiogram' },
  { abbreviation: 'ECLS', definition: 'Extracorporeal life support' },
  { abbreviation: 'ECMO', definition: 'Extracorporeal membrane oxygenation' },
  { abbreviation: 'ECT', definition: 'Electroconvulsive therapy' },
  { abbreviation: 'ECV', definition: 'External cephalic version' },
  { abbreviation: 'EDD', definition: 'Estimated date of delivery' },
  { abbreviation: 'EEG', definition: 'Electroencephalogram' },
  { abbreviation: 'EER', definition: 'Estimated energy requirements' },
  { abbreviation: 'EFA', definition: 'Essential fatty acids' },
  { abbreviation: 'EFM', definition: 'Electronic fetal monitoring' },
  { abbreviation: 'EFW', definition: 'Estimated fetal weight' },
  { abbreviation: 'EGA', definition: 'Estimated gestational age' },
  { abbreviation: 'EHL', definition: 'Extensor hallucis longus' },
  { abbreviation: 'EMG', definition: 'Electromyography' },
  { abbreviation: 'EMS', definition: 'Elderly mobility scale' },
  { abbreviation: 'EMU', definition: 'Early morning urine' },
  { abbreviation: 'ENT', definition: 'Ear nose and throat' },
  { abbreviation: 'EOM', definition: 'External ocular movements' },
  { abbreviation: 'EOR', definition: 'End of range' },
  { abbreviation: 'EPAU', definition: 'Early Pregnancy Assessment unit' },
  { abbreviation: 'EPL', definition: 'Extensor pollicus longus' },
  { abbreviation: 'EPS', definition: 'Electrophysiology studies' },
  { abbreviation: 'ERCP', definition: 'Endoscopic retrograde cholangio-pancreatography' },
  { abbreviation: 'ERPC', definition: 'Evacuation of retained products of conception' },
  { abbreviation: 'ESKD', definition: 'End stage kidney disease' },
  { abbreviation: 'ESR', definition: 'Erythrocyte sedimentation rate' },
  { abbreviation: 'EST', definition: 'Exercise stress test' },
  { abbreviation: 'ESWL', definition: 'External shock wave lithotripsy' },
  { abbreviation: 'EUA', definition: 'Examination under anaesthetic' },
  { abbreviation: 'EUM', definition: 'Examination under microscope' },
  { abbreviation: 'EVAR', definition: 'Endovascular aneurysm repair' },
  { abbreviation: 'EVLT', definition: 'Endovenous laser therapy' },
  { abbreviation: 'FAD', definition: 'Focus to axis distance' },
  { abbreviation: 'FAS', definition: 'Fetal assessment scan' },
  { abbreviation: 'FBC', definition: 'Full blood count' },
  { abbreviation: 'FBM', definition: 'Fetal breathing movement' },
  { abbreviation: 'FBS', definition: 'Fasting blood sugar' },
  { abbreviation: 'FDP', definition: 'Fibrin degredation products' },
  { abbreviation: 'FDS', definition: 'Flexor digitorum superficialis' },
  { abbreviation: 'FEES', definition: 'Fibreoptic endoscopic examination of the swallow' },
  { abbreviation: 'FES', definition: 'Functional electrical stimulation' },
  { abbreviation: 'FESS', definition: 'Functional Endoscopic Sinus Surgery' },
  { abbreviation: 'FET', definition: 'Forced expiratory technique' },
  { abbreviation: 'FFD', definition: 'Fixed flexion deformity' },
  { abbreviation: 'FFP', definition: 'Fresh frozen plasma' },
  { abbreviation: 'FHH', definition: 'Fetal heart heard' },
  { abbreviation: 'FHHR', definition: 'Fetal heart heard and regular' },
  { abbreviation: 'FHNH', definition: 'Fetal heart not heard' },
  { abbreviation: 'FHR', definition: 'Fetal heart rate' },
  { abbreviation: 'FLP', definition: 'Fasting lipid profile' },
  { abbreviation: 'FMF', definition: 'Fetal movement felt' },
  { abbreviation: 'FNA', definition: 'Fine needle aspiration' },
  { abbreviation: 'FNAB', definition: 'Fine needle aspirate biopsy' },
  { abbreviation: 'FOB', definition: 'Faecal occult blood' },
  { abbreviation: 'FROM', definition: 'Full range of movement/motion' },
  { abbreviation: 'FSE', definition: 'Fetal scalp electrode' },
  { abbreviation: 'FSH', definition: 'Follicle stimulating hormone' },
  { abbreviation: 'FTA', definition: 'Failure to advance' },
  { abbreviation: 'FTND', definition: 'Full term normal delivery' },
  { abbreviation: 'FTT', definition: 'Failure to thrive' },
  { abbreviation: 'FVC', definition: 'Forced vital capacity' },
  { abbreviation: 'FWB', definition: 'Full weight bearing' },
  { abbreviation: 'GBS', definition: 'Group B streptococcus' },
  { abbreviation: 'GCS', definition: 'Glasgow coma scale' },
  { abbreviation: 'GCSF', definition: 'Granulocyte colony stimulating factor' },
  { abbreviation: 'GCT', definition: 'Glucose challenge test' },
  { abbreviation: 'GDM', definition: 'gestational diabetes mellitus' },
  { abbreviation: 'GFR', definition: 'glomerular filtration rate' },
  { abbreviation: 'GHJ', definition: 'gleno-humeral joint' },
  { abbreviation: 'GIT', definition: 'gastro-intestinal tract' },
  { abbreviation: 'GORD', definition: 'gastro-oesophageal reflux disorder/disease' },
  { abbreviation: 'GTN', definition: 'glyceryl Tri-Nitrate' },
  { abbreviation: 'GTT', definition: 'glucose tolerance test' },
  { abbreviation: 'GUM', definition: 'genito-urinary medicine' },
  { abbreviation: 'GUR', definition: 'genito-ureteric reflux' },
  { abbreviation: 'GVHD', definition: 'graft versus host disease' },
  { abbreviation: 'GXM', definition: 'group and cross match' },
  { abbreviation: 'GZF', definition: 'gutter zimmer frame' },
  { abbreviation: 'HAV', definition: 'Hepatitis A virus' },
  { abbreviation: 'HBB', definition: 'Hand behind back' },
  { abbreviation: 'HBH', definition: 'Hand behind head' },
  { abbreviation: 'HBV', definition: 'Hepatitis B virus' },
  { abbreviation: 'HCA', definition: 'Home care assistant' },
  { abbreviation: 'HCG', definition: 'Human chorionic gonadotropin' },
  { abbreviation: 'HCV', definition: 'Hepatitis C virus' },
  { abbreviation: 'HDL', definition: 'High density lipoprotein' },
  { abbreviation: 'HDU', definition: 'High Dependency unit' },
  { abbreviation: 'HEP', definition: 'Home exercise programme' },
  { abbreviation: 'HFOV', definition: 'High frequency oscillator ventilator' },
  { abbreviation: 'HIE', definition: 'Hypoxic ischaemic encephalopathy' },
  { abbreviation: 'HIPE', definition: 'Hospital In Patient Enquiry' },
  { abbreviation: 'HIT', definition: 'Heparin induced thrombocytopenia' },
  { abbreviation: 'HITS', definition: 'Heparin induced thrombocytopenia syndrome' },
  { abbreviation: 'HIV', definition: 'Human immunodeficiency virus' },
  { abbreviation: 'HLA', definition: 'Human lucocyte antigen' },
  { abbreviation: 'HMD', definition: 'Hyaline membrane disease' },
  { abbreviation: 'HPHC', definition: 'High protein high calorie' },
  { abbreviation: 'HPOA', definition: 'Hypertrophic Pulmonary Osteoarthropathy' },
  { abbreviation: 'HRT', definition: 'Hormone replacement therapy' },
  { abbreviation: 'HSE', definition: 'Health Service Executive' },
  { abbreviation: 'HSP', definition: 'Henock schonlein purpura' },
  { abbreviation: 'HTN', definition: 'Hypertension' },
  { abbreviation: 'HUS', definition: 'Haemolytic uraemic syndrome' },
  { abbreviation: 'HVS', definition: 'High vaginal swab' },
  { abbreviation: 'IABP', definition: 'Intra-aortic Balloon Pump' },
  { abbreviation: 'IAS', definition: 'Interatrial septum' },
  { abbreviation: 'IBW', definition: 'Ideal body weight' },
  { abbreviation: 'ICP', definition: 'Intracranial pressure' },
  { abbreviation: 'ICU', definition: 'Intensive Care unit' },
  { abbreviation: 'IDPN', definition: 'Intradialytic parenteral nutrition' },
  { abbreviation: 'IDWG', definition: 'Intradialytic weight gain' },
  { abbreviation: 'IFT', definition: 'Interferential therapy' },
  { abbreviation: 'IHD', definition: 'Ischaemic heart disease' },
  { abbreviation: 'IHF', definition: 'Irish Heart Foundation' },
  { abbreviation: 'IMB', definition: 'Intermenstrual bleeding' },
  { abbreviation: 'IMV', definition: 'Intermittent mandatory ventilation' },
  { abbreviation: 'INR', definition: 'International normalised ratio' },
  { abbreviation: 'IOL', definition: 'Induction of labour' },
  { abbreviation: 'IOP', definition: 'Intra ocular pressure' },
  { abbreviation: 'IPD', definition: 'Intermittent peritoneal dialysis' },
  { abbreviation: 'IPJ', definition: 'Interphalangeal joint' },
  { abbreviation: 'IPPB', definition: 'Intermittent positive pressure breathing' },
  { abbreviation: 'IPPV', definition: 'Intermittent positive pressure ventilation' },
  { abbreviation: 'IRQ', definition: 'Inner range quadriceps' },
  { abbreviation: 'ISC', definition: 'Intermittent self catheterisation' },
  { abbreviation: 'ISQ', definition: 'In Status Quo' },
  { abbreviation: 'ITP', definition: 'Idiopathic thrombocytopenia purpura' },
  { abbreviation: 'ITT', definition: 'Insulin tolerance test' },
  { abbreviation: 'ITU', definition: 'Intensive Therapy unit' },
  { abbreviation: 'IUCD', definition: 'Intrauterine contraceptive device' },
  { abbreviation: 'IUD', definition: 'Intrauterine death' },
  { abbreviation: 'IUGR', definition: 'Intrauterine growth retardation/restriction' },
  { abbreviation: 'IVC', definition: 'Inferior vena cava' },
  { abbreviation: 'IVDU', definition: 'Intravenous drug user' },
  { abbreviation: 'IVF', definition: 'In vitro Fertilisation' },
  { abbreviation: 'IVH', definition: 'Intraventricular haemorrhage' },
  { abbreviation: 'IVI', definition: 'Intravenous infusion' },
  { abbreviation: 'IVP', definition: 'Intravenous pyelogram' },
  { abbreviation: 'IVS', definition: 'Interventricular septum' },
  { abbreviation: 'IVSD', definition: 'Interventricular septum in diastole' },
  { abbreviation: 'IVSS', definition: 'Interventricular wall in systole' },
  { abbreviation: 'IVT', definition: 'Intravenous therapy' },
  { abbreviation: 'IVU', definition: 'Intravenous urogram' },
  { abbreviation: 'IVUS', definition: 'Intravascular ultrasound' },
  { abbreviation: 'IWA', definition: 'Irish Wheelchair Association' },
  { abbreviation: 'JIA', definition: 'Juvenile idiopathic arthritis' },
  { abbreviation: 'JVP', definition: 'Jugular venous pressure' },
  { abbreviation: 'KAFO', definition: 'knee ankle foot orthosis' },
  { abbreviation: 'KCL', definition: 'Potassium chloride' },
  { abbreviation: 'KUB', definition: 'kidneys, ureters and bladder' },
  { abbreviation: 'KVO', definition: 'keep vein open' },
  { abbreviation: 'LAA', definition: 'Left atrial appendage' },
  { abbreviation: 'LADA', definition: 'Left anterior descending artery' },
  { abbreviation: 'LAVH', definition: 'Laparoscopic assisted vaginal hysterectomy' },
  { abbreviation: 'LBBB', definition: 'Left bundle branch block' },
  { abbreviation: 'LBM', definition: 'Lean body mass' },
  { abbreviation: 'LBP', definition: 'Low back pain' },
  { abbreviation: 'LCL', definition: 'Lateral collateral ligament' },
  { abbreviation: 'LCT', definition: 'Long chain triglyceride' },
  { abbreviation: 'LCX', definition: 'Circumflex artery' },
  { abbreviation: 'LDH', definition: 'Lactate dehydrogenase' },
  { abbreviation: 'LDL', definition: 'Low density lipoprotein' },
  { abbreviation: 'LGA', definition: 'Large for gestational age' },
  { abbreviation: 'LHS', definition: 'Left height sensation' },
  { abbreviation: 'LIF', definition: 'Left iliac fossa' },
  { abbreviation: 'LIH', definition: 'Left inguinal hernia' },
  { abbreviation: 'LLQ', definition: 'Left lower quadrant' },
  { abbreviation: 'LMA', definition: 'Laryngeal mask airway' },
  { abbreviation: 'LMP', definition: 'Last menstrual period' },
  { abbreviation: 'LOA', definition: 'Left occipito-anterior' },
  { abbreviation: 'LOC', definition: 'Loss of consciousness' },
  { abbreviation: 'LOL', definition: 'Left occipito-lateral' },
  { abbreviation: 'LOP', definition: 'Left occipito-posterior' },
  { abbreviation: 'LOR', definition: 'Loss of resistance' },
  { abbreviation: 'LRTI', definition: 'Lower respiratory tract infection' },
  { abbreviation: 'LSA', definition: 'Left sacro-anterior' },
  { abbreviation: 'LSCS', definition: 'Lower segment caesarean section' },
  { abbreviation: 'LSF', definition: 'Left side flexion' },
  { abbreviation: 'LSH', definition: 'Long shoe horn' },
  { abbreviation: 'LSL', definition: 'Left sacro-lateral' },
  { abbreviation: 'LSO', definition: 'Left salpingo-oophorectomy' },
  { abbreviation: 'LSP', definition: 'Left sacro-posterior' },
  { abbreviation: 'LTM', definition: 'Long term care' },
  { abbreviation: 'LTM', definition: 'Long term memory' },
  { abbreviation: 'LTS', definition: 'Lateral tarsal strip' },
  { abbreviation: 'LUQ', definition: 'Left upper quadrant' },
  { abbreviation: 'LUS', definition: 'Lower uterine segment' },
  { abbreviation: 'LVAD', definition: 'Left ventricular assist device' },
  { abbreviation: 'LVDV', definition: 'Left ventricular diastolic volume' },
  { abbreviation: 'LVF', definition: 'Left ventricular failure' },
  { abbreviation: 'LVH', definition: 'Left ventricular hypertrophy' },
  { abbreviation: 'LVOT', definition: 'Left ventricular outflow tract' },
  { abbreviation: 'LVS', definition: 'Low vaginal swab' },
  { abbreviation: 'LVSV', definition: 'Left ventricle systolic volume' },
  { abbreviation: 'MAP', definition: 'Mean arterial pressure' },
  { abbreviation: 'MAS', definition: 'Motor assessment scale' },
  { abbreviation: 'MAU', definition: 'Medical Assessment/Admission unit' },
  { abbreviation: 'MCA', definition: 'Middle cerebral artery' },
  { abbreviation: 'MCL', definition: 'Medial collateral ligament' },
  { abbreviation: 'MCPJ', definition: 'Metacarpo-phalangeal joint' },
  { abbreviation: 'MCUG', definition: 'Micturating cystourethrogram' },
  { abbreviation: 'MCV', definition: 'Mean corpuscular volume' },
  { abbreviation: 'MDA', definition: 'Misuse of Drugs Act' },
  { abbreviation: 'MDT', definition: 'Multidisciplinary team' },
  { abbreviation: 'MDU', definition: 'Medical Day unit' },
  { abbreviation: 'MFR', definition: 'Maximum flow rate' },
  { abbreviation: 'MLB', definition: 'Micro laryngeal bronchoscopy' },
  { abbreviation: 'MMK', definition: 'Marshall Marchetti krantz' },
  { abbreviation: 'MMR', definition: 'Measles, mumps, rubella' },
  { abbreviation: 'MMSE', definition: 'Mini mental state examination' },
  { abbreviation: 'MNB', definition: 'Manipulation of nasal bones' },
  { abbreviation: 'MND', definition: 'Motor neurone disease' },
  { abbreviation: 'MPT', definition: 'Maximum phonation time' },
  { abbreviation: 'MRCP', definition: 'Magnetic resonance cholangiopancreatography' },
  { abbreviation: 'MRI', definition: 'Magnetic resonance imaging' },
  { abbreviation: 'MROP', definition: 'Manual removal of placenta' },
  { abbreviation: 'MRSA', definition: 'Methicillin resistant staphylococcus aureus' },
  { abbreviation: 'MSSA', definition: 'Methicillin sensitive staphylococcus aureus' },
  { abbreviation: 'MSU', definition: 'Midstream specimen of urine' },
  { abbreviation: 'MSW', definition: 'Medical Social Worker' },
  { abbreviation: 'MTPJ', definition: 'Metatarso-phalangeal joint' },
  { abbreviation: 'MUA', definition: 'Manipulation under anaesthetic' },
  { abbreviation: 'MUFA', definition: 'Mono unsaturated fatty acids' },
  { abbreviation: 'MUGA', definition: 'Multiple-gated arteriography' },
  { abbreviation: 'MVA', definition: 'Mitral valve area' },
  { abbreviation: 'MVR', definition: 'Mitral valve replacement' },
  { abbreviation: 'MWM', definition: 'Mobilisation with movement' },
  { abbreviation: 'NAD', definition: 'No abnormality detected' },
  { abbreviation: 'NAG', definition: 'Natural apophyseal glide' },
  { abbreviation: 'NAI', definition: 'Non accidental injury' },
  { abbreviation: 'NAS', definition: 'Neonatal abstinence syndrome' },
  { abbreviation: 'NBFD', definition: 'Neville Barnes forceps delivery' },
  { abbreviation: 'NCA', definition: 'Nurse controlled analgesia' },
  { abbreviation: 'NCHD', definition: 'Non consultant hospital doctor' },
  { abbreviation: 'NEC', definition: 'Necrotising enterocolitis' },
  { abbreviation: 'NETZ', definition: 'Needle excision of transformation zone' },
  { abbreviation: 'NFA', definition: 'No fixed abode' },
  { abbreviation: 'NFR', definition: 'Not for resuscitation' },
  { abbreviation: 'NHL', definition: 'Non hodgkins lymphoma' },
  { abbreviation: 'NIBP', definition: 'Non invasive blood pressure' },
  { abbreviation: 'NICU', definition: 'Neonatal Intensive Care unit' },
  { abbreviation: 'NIEL', definition: 'Not in established labour' },
  { abbreviation: 'NIV', definition: 'Non invasive ventilation' },
  { abbreviation: 'NKA', definition: 'No known allergies' },
  { abbreviation: 'NKDA', definition: 'No known drug allergies' },
  { abbreviation: 'NMS', definition: 'Neuroleptic malignant syndrome' },
  { abbreviation: 'NND', definition: 'Neonatal death' },
  { abbreviation: 'NOF', definition: 'Neck of femur' },
  { abbreviation: 'NOK', definition: 'Next of kin' },
  { abbreviation: 'NPL', definition: 'No perception of light' },
  { abbreviation: 'NPO', definition: 'Nil per oral' },
  { abbreviation: 'NPU', definition: 'Not passed urine' },
  { abbreviation: 'NSR', definition: 'Normal sinus rhythm' },
  { abbreviation: 'NTD', definition: 'Neural tube defect' },
  { abbreviation: 'NTT', definition: 'Nasotracheal tube' },
  { abbreviation: 'NWB', definition: 'Non weight bearing' },
  { abbreviation: 'OCP', definition: 'Oral contraceptive pill' },
  { abbreviation: 'OCPD', definition: 'Optichoice peritoneal dialysis' },
  { abbreviation: 'OFC', definition: 'Occipito-frontal circumference' },
  { abbreviation: 'OGD', definition: 'Oesophago-gastro- duodenoscopy' },
  { abbreviation: 'OGTT', definition: 'Oral glucose tolerance test' },
  { abbreviation: 'OHA', definition: 'Oral hypoglycaemic agent' },
  { abbreviation: 'OHSS', definition: 'Ovarian hyperstimulation syndrome' },
  { abbreviation: 'OPD', definition: 'Outpatient Department' },
  { abbreviation: 'OPE', definition: 'Oral peripheral examination' },
  { abbreviation: 'ORIF', definition: 'Open reduction and internal fixation' },
  { abbreviation: 'ORQ', definition: 'Outer range quadriceps' },
  { abbreviation: 'PAC', definition: 'Premature atrial contraction' },
  { abbreviation: 'PADL', definition: 'Personal activities of daily living' },
  { abbreviation: 'PAF', definition: 'Paroxysmal atrial fibrillation' },
  { abbreviation: 'PASP', definition: 'Pulmonary artery systolic pressure' },
  { abbreviation: 'PCA', definition: 'Patient controlled analgesia' },
  { abbreviation: 'PCEA', definition: 'Patient controlled epidural analgesia' },
  { abbreviation: 'PCI', definition: 'Percutaneous coronary intervention' },
  { abbreviation: 'PCL', definition: 'Posterior cruciate ligament' },
  { abbreviation: 'PCR', definition: 'Polymerase chain reaction' },
  { abbreviation: 'PCV', definition: 'Packed cell volume' },
  { abbreviation: 'PDA', definition: 'Posterior descending artery' },
  { abbreviation: 'PDPH', definition: 'Postdural puncture headache' },
  { abbreviation: 'PEA', definition: 'Pulseless electrical activity' },
  { abbreviation: 'PEEP', definition: 'Positive end expiratory pressure' },
  { abbreviation: 'PEFR', definition: 'Peak expiratory flow rate' },
  { abbreviation: 'PEG', definition: 'Percutaneous endoscopic gastrostomy' },
  { abbreviation: 'PEJ', definition: 'Percutaneous endoscopic jejunostomy' },
  { abbreviation: 'PEM', definition: 'Protein energy malnutrition' },
  { abbreviation: 'PERT', definition: 'Pancreatic enzyme replacement therapy' },
  { abbreviation: 'PFA', definition: 'Plain film of abdomen' },
  { abbreviation: 'PFJ', definition: 'Patellofemoral joint' },
  { abbreviation: 'PFO', definition: 'Patent foramen ovale' },
  { abbreviation: 'PFR', definition: 'Pelvic floor repair' },
  { abbreviation: 'PGE', definition: 'Prostaglandin E' },
  { abbreviation: 'PHN', definition: 'Public Health Nurse' },
  { abbreviation: 'PHT', definition: 'Pulmonary hypertension' },
  { abbreviation: 'PICC', definition: 'Peripherally inserted central catheter' },
  { abbreviation: 'PICU', definition: 'Paediatric Intensive Care unit' },
  { abbreviation: 'PID', definition: 'Pelvic inflammatory disease' },
  { abbreviation: 'PIH', definition: 'Pregnancy induced hypertension' },
  { abbreviation: 'PIIS', definition: 'Posterior inferior iliac spine' },
  { abbreviation: 'PIP', definition: 'Peak inspiratory pressure' },
  { abbreviation: 'PIPJ', definition: 'Proximal interphalangeal joint' },
  { abbreviation: 'PKB', definition: 'Prone knee bend' },
  { abbreviation: 'PKU', definition: 'Phenylketonuria' },
  { abbreviation: 'PLAD', definition: 'Posterior lip augmentation device' },
  { abbreviation: 'PLIF', definition: 'Posterior lumbar intervertebral fusion' },
  { abbreviation: 'PLO', definition: 'Pharyngolaryngoesophagectomy' },
  { abbreviation: 'PLTS', definition: 'Platelets' },
  { abbreviation: 'PMB', definition: 'Post menopausal bleeding' },
  { abbreviation: 'PND', definition: 'Paroxysmal nocturnal dyspnoea' },
  { abbreviation: 'PNF', definition: 'Proprioceptive neuromuscular facilitation' },
  { abbreviation: 'POA', definition: 'Persistant occipito-anterior' },
  { abbreviation: 'POD', definition: 'Progression of disease' },
  { abbreviation: 'POP', definition: 'Plaster of paris' },
  { abbreviation: 'PPH', definition: 'Post-partum haemorrhage' },
  { abbreviation: 'PPHN', definition: 'Persistent pulmonary hypertension of the newborn' },
  { abbreviation: 'PPN', definition: 'Peripheral parenteral nutrition' },
  { abbreviation: 'PPV', definition: 'Pars plana vitrectomy' },
  { abbreviation: 'PROM', definition: 'Prolonged rupture of membranes' },
  { abbreviation: 'PRP', definition: 'Pan retinal photocoagulation' },
  { abbreviation: 'PSA', definition: 'Prostatic specific antigen' },
  { abbreviation: 'PSIS', definition: 'Posterior superior iliac spine' },
  { abbreviation: 'PSV', definition: 'Pressure support ventilation' },
  { abbreviation: 'PSW', definition: 'Psychiatric Social Worker' },
  { abbreviation: 'PSWD', definition: 'Pulsed short wave diathermy' },
  { abbreviation: 'PTA', definition: 'Post traumatic amnesia' },
  { abbreviation: 'PTB', definition: 'Patella tendon bearing' },
  { abbreviation: 'PTCA', definition: 'Percutaneous transluminal coronary angioplasty' },
  { abbreviation: 'PTSD', definition: 'Post traumatic stress disorder' },
  { abbreviation: 'PTT', definition: 'Partial thromboplastin time' },
  { abbreviation: 'PTTK', definition: 'Partial thromboplastin time kaolin' },
  { abbreviation: 'PUD', definition: 'Peptic ulcer disease' },
  { abbreviation: 'PUFA', definition: 'Polyunsaturated fatty acids' },
  { abbreviation: 'PUJ', definition: 'Pelvic-ureteric junction' },
  { abbreviation: 'PUO', definition: 'Pyrexia of unknown origin' },
  { abbreviation: 'PVC', definition: 'Premature ventricular contraction' },
  { abbreviation: 'PVD', definition: 'Peripheral vascular disease' },
  { abbreviation: 'PVL', definition: 'Periventricular leucomalacia' },
  { abbreviation: 'PWB', definition: 'Partial weight bearing' },
  { abbreviation: 'PWD', definition: 'Posterior wall in diastole' },
  { abbreviation: 'PWS', definition: 'Posterior wall in systole' },
  { abbreviation: 'QRS', definition: 'Deflection on Ekg representing electrical activity' },
  { abbreviation: 'RBBB', definition: 'Right bundle branch block' },
  { abbreviation: 'RBC', definition: 'Red blood cells' },
  { abbreviation: 'RBG', definition: 'Random blood glucose' },
  { abbreviation: 'RCA', definition: 'Right coronary artery' },
  { abbreviation: 'RCC', definition: 'Red cell concentrate' },
  { abbreviation: 'RCJ', definition: 'Radio-carpal joint' },
  { abbreviation: 'RCN', definition: 'Registered Childrens Nurse' },
  { abbreviation: 'RDS', definition: 'Respiratory distress syndrome' },
  { abbreviation: 'REE', definition: 'Resting energy expenditure' },
  { abbreviation: 'REM', definition: 'Rapid eye movement' },
  { abbreviation: 'RFA', definition: 'Radio frequency ablation' },
  { abbreviation: 'RGN', definition: 'Registered general Nurse' },
  { abbreviation: 'RHS', definition: 'Right height sensation' },
  { abbreviation: 'RICE', definition: 'Rest, ice, compression, elevation' },
  { abbreviation: 'RIF', definition: 'Right iliac fossa' },
  { abbreviation: 'RIG', definition: 'Radiology inserted gastrostomy' },
  { abbreviation: 'RIH', definition: 'Right inguinal hernia' },
  { abbreviation: 'RIP', definition: 'Rest in peace/Deceased' },
  { abbreviation: 'RLQ', definition: 'Right lower quadrant' },
  { abbreviation: 'RNI', definition: 'Reference nutrient intake' },
  { abbreviation: 'RNID', definition: 'Registered Nurse Intellectual Disability' },
  { abbreviation: 'RNP', definition: 'Registered Nurse Prescriber' },
  { abbreviation: 'RNT', definition: 'Registered Nurse Tutor' },
  { abbreviation: 'ROA', definition: 'Right occipito-anterior' },
  { abbreviation: 'ROL', definition: 'Right occipito-lateral' },
  { abbreviation: 'ROM', definition: 'Range of movement/motion' },
  { abbreviation: 'ROP', definition: 'Right occipito-posterior' },
  { abbreviation: 'ROS', definition: 'Removal of sutures' },
  { abbreviation: 'RPN', definition: 'Registered Psychiatric Nurse' },
  { abbreviation: 'RRT', definition: 'Renal replacement therapy' },
  { abbreviation: 'RSA', definition: 'Right sacro-anterior' },
  { abbreviation: 'RSD', definition: 'Reflex sympathetic dystrophy' },
  { abbreviation: 'RSF', definition: 'Right side flexion' },
  { abbreviation: 'RSI', definition: 'Repetitive strain injury' },
  { abbreviation: 'RSO', definition: 'Right salpingo-oophorectomy' },
  { abbreviation: 'RSP', definition: 'Right sacro-posterior' },
  { abbreviation: 'RSV', definition: 'Respiratory syncytial virus' },
  { abbreviation: 'RTA', definition: 'Road traffic accident' },
  { abbreviation: 'RTI', definition: 'Respiratory tract infection' },
  { abbreviation: 'RTS', definition: 'Raised toilet seat' },
  { abbreviation: 'RTW', definition: 'Returned to ward' },
  { abbreviation: 'RUJ', definition: 'Radio-ulnar joint' },
  { abbreviation: 'RUQ', definition: 'Right upper quadrant' },
  { abbreviation: 'RVDV', definition: 'Right ventricle diastolic volume' },
  { abbreviation: 'RVF', definition: 'Right ventricular failure' },
  { abbreviation: 'RVH', definition: 'Right ventricular hypertrophy' },
  { abbreviation: 'RVOT', definition: 'Right ventricular outflow tract' },
  { abbreviation: 'RVSP', definition: 'Right ventricular systolic pressure' },
  { abbreviation: 'RVSV', definition: 'Right ventricle systolic volume' },
  { abbreviation: 'RZF', definition: 'Rollator zimmer frame' },
  { abbreviation: 'SAD', definition: 'Seasonal affective disorder' },
  { abbreviation: 'SAH', definition: 'Sub arachnoid haemorrhage' },
  { abbreviation: 'SARS', definition: 'Severe acute respiratory syndrome' },
  { abbreviation: 'SBA', definition: 'Stand-by assistance' },
  { abbreviation: 'SBBE', definition: 'Small bowel barium enema' },
  { abbreviation: 'SBE', definition: 'Subacute bacterial endocarditis' },
  { abbreviation: 'SBFT', definition: 'Small bowel follow through' },
  { abbreviation: 'SBR', definition: 'Serum bilirubin rate' },
  { abbreviation: 'SCBU', definition: 'Special Care Baby unit' },
  { abbreviation: 'SCC', definition: 'Spinal cord compression' },
  { abbreviation: 'SCD', definition: 'Sickle cell disease' },
  { abbreviation: 'SCJ', definition: 'Sterno-clavicular joint' },
  { abbreviation: 'SFA', definition: 'Saturated fatty acids' },
  { abbreviation: 'SFD', definition: 'Small for dates' },
  { abbreviation: 'SGA', definition: 'Small for gestational age' },
  { abbreviation: 'SHO', definition: 'Senior House Officer' },
  { abbreviation: 'SIC', definition: 'Self-intermittent catheterisation' },
  { abbreviation: 'SIDS', definition: 'Sudden infant death syndrome' },
  { abbreviation: 'SIJ', definition: 'Sacroiliac joint' },
  { abbreviation: 'SIMV', definition: 'Synchronised intermittent mandatory ventilation' },
  { abbreviation: 'SLE', definition: 'Systemic lupus erythematosus' },
  { abbreviation: 'SLR', definition: 'Straight leg raise' },
  { abbreviation: 'SLT', definition: 'Speech and Language Therapy/Therapist' },
  { abbreviation: 'SMD', definition: 'Sub-mucosal diathermy' },
  { abbreviation: 'SMR', definition: 'Sub-mucosal resection' },
  { abbreviation: 'SNAG', definition: 'Sustained natural apophyseal glide' },
  { abbreviation: 'SOB', definition: 'Shortness of breath' },
  { abbreviation: 'SOP', definition: 'Standard operating procedure' },
  { abbreviation: 'SRF', definition: 'Sub retinal fluid' },
  { abbreviation: 'SROM', definition: 'Spontaneous rupture of membranes' },
  { abbreviation: 'SSD', definition: 'Source to skin distance' },
  { abbreviation: 'SSG', definition: 'Split skin graft' },
  { abbreviation: 'SSM', definition: 'Senior Staff Midwife' },
  { abbreviation: 'SSN', definition: 'Senior Staff Nurse' },
  { abbreviation: 'SSPE', definition: 'Subacute sclerosing panencephalitis' },
  { abbreviation: 'STAH', definition: 'Subtotal abdominal hysterectomy' },
  { abbreviation: 'STAR', definition: 'Scandinavian total ankle replacement' },
  { abbreviation: 'STI', definition: 'Sexually transmitted infection' },
  { abbreviation: 'STJ', definition: 'Sub-talor joint' },
  { abbreviation: 'STM', definition: 'Short term memory' },
  { abbreviation: 'STNR', definition: 'Symmetric tonic neck reflex' },
  { abbreviation: 'STR', definition: 'Soft tissue release' },
  { abbreviation: 'SUI', definition: 'Stress urinary incontinence' },
  { abbreviation: 'SVC', definition: 'Superior vena cava' },
  { abbreviation: 'SVCO', definition: 'Superior vena cava obstruction' },
  { abbreviation: 'SVD', definition: 'Spontaneous vaginal delivery' },
  { abbreviation: 'SVRA', definition: 'Self-ventilating on room air' },
  { abbreviation: 'SVT', definition: 'Supra ventricular tachycardia' },
  { abbreviation: 'SWD', definition: 'Shortwave diathermy' },
  { abbreviation: 'TAH', definition: 'Total abdominal hysterectomy' },
  { abbreviation: 'TAR', definition: 'Total ankle replacement' },
  { abbreviation: 'TBC', definition: 'Tuberculin bacillus culture' },
  { abbreviation: 'TBI', definition: 'Traumatic brain injury' },
  { abbreviation: 'TBG', definition: 'True blood glucose' },
  { abbreviation: 'TBL', definition: 'Total blood loss' },
  { abbreviation: 'TBW', definition: 'Tension band wiring' },
  { abbreviation: 'TCM', definition: 'Transcutaneous monitor' },
  { abbreviation: 'TCOM', definition: 'Transcutaneous oxygen monitoring' },
  { abbreviation: 'TCRE', definition: 'Transcervical resection of endometrium' },
  { abbreviation: 'TEE', definition: 'Total energy expenditure' },
  { abbreviation: 'TENS', definition: 'Transcutaneous electrical nerve stimulation' },
  { abbreviation: 'TEP', definition: 'Tracheoesophageal puncture' },
  { abbreviation: 'TER', definition: 'Total elbow replacement' },
  { abbreviation: 'TES', definition: 'Therapeutic endoscopic sialalendoscopy' },
  { abbreviation: 'TFA', definition: 'Trans fatty acids' },
  { abbreviation: 'TFVT', definition: 'Tension free vaginal tape' },
  { abbreviation: 'TGA', definition: 'Transposition of the great arteries' },
  { abbreviation: 'THR', definition: 'Total Hip Replacement' },
  { abbreviation: 'TIA', definition: 'Transient ischaemic attack' },
  { abbreviation: 'TIBC', definition: 'Total iron binding capacity' },
  { abbreviation: 'TICH', definition: 'Traumatic intracranial haemorrhage' },
  { abbreviation: 'TKR', definition: 'Total knee Replacement' },
  { abbreviation: 'TMD', definition: 'Thyromental distance' },
  { abbreviation: 'TMJ', definition: 'Tempero-mandibular joint' },
  { abbreviation: 'TMP', definition: 'Transmembrane pressure' },
  { abbreviation: 'TOE', definition: 'Trans oesophageal echocardiogram' },
  { abbreviation: 'TOF', definition: 'Tracheoesophageal fistula' },
  { abbreviation: 'TOP', definition: 'Termination of pregnancy' },
  { abbreviation: 'TPHA', definition: 'Teponema pallidum haemagglutination' },
  { abbreviation: 'TPN', definition: 'Total parenteral nutrition' },
  { abbreviation: 'TPR', definition: 'Temperature, pulse and respiration' },
  { abbreviation: 'TRH', definition: 'Thyrotrophin releasing hormone' },
  { abbreviation: 'TSH', definition: 'Thyroid stimulating hormone' },
  { abbreviation: 'TSR', definition: 'Total shoulder replacement' },
  { abbreviation: 'TTN', definition: 'Transient tachypnoea of the newborn' },
  { abbreviation: 'TTWB', definition: 'Toe touch weight bearing' },
  { abbreviation: 'TUAG', definition: 'Timed up and go test' },
  { abbreviation: 'TURB', definition: 'Transurethral resection of prostate' },
  { abbreviation: 'TVI', definition: 'Tissue velocity imaging' },
  { abbreviation: 'TVS', definition: 'Transvaginal scan' },
  { abbreviation: 'UAC', definition: 'umbilical arterial catheter' },
  { abbreviation: 'UBW', definition: 'usual body weight' },
  { abbreviation: 'ULTT', definition: 'upper limb tension test' },
  { abbreviation: 'UPPP', definition: 'uvulopalatopharyngoplasty' },
  { abbreviation: 'URTI', definition: 'upper respiratory tract infection' },
  { abbreviation: 'USS', definition: 'Ultrasound scan' },
  { abbreviation: 'UST', definition: 'ultrasound therapy' },
  { abbreviation: 'UTI', definition: 'urinary tract infection' },
  { abbreviation: 'UVC', definition: 'umbilical venous catheter' },
  { abbreviation: 'UVJ', definition: 'uretero-vesical junction' },
  { abbreviation: 'UWSD', definition: 'underwater seal drain' },
  { abbreviation: 'VAS', definition: 'Visual analogue scale' },
  { abbreviation: 'VBAC', definition: 'Vaginal birth after caesarean section' },
  { abbreviation: 'VBG', definition: 'Venous blood gas' },
  { abbreviation: 'VCJD', definition: 'Variant Crutzfeldt Jakob Disease' },
  { abbreviation: 'VDRL', definition: 'Venereal disease research laboratory test' },
  { abbreviation: 'VFU', definition: 'Videofluoroscopy' },
  { abbreviation: 'VHI', definition: 'Voluntary Health Insurance' },
  { abbreviation: 'VIN', definition: 'Vulval intraepithelial neoplasia' },
  { abbreviation: 'VLCD', definition: 'Very low calorie diet' },
  { abbreviation: 'VMA', definition: 'Vanillylmandelic acid' },
  { abbreviation: 'VML', definition: 'Vastus medialis longus' },
  { abbreviation: 'VMO', definition: 'Vastus medialis oblique' },
  { abbreviation: 'VRE', definition: 'Vancomycin resistant enteroccocus' },
  { abbreviation: 'VSB', definition: 'Videostroboscopy' },
  { abbreviation: 'VSD', definition: 'Ventricular septal defect' },
  { abbreviation: 'VVF', definition: 'Vesico vaginal fistula' },
  { abbreviation: 'VZIG', definition: 'Varicella zoster immune globulin' },
  { abbreviation: 'WBC', definition: 'Whole blood count' },
  { abbreviation: 'WCC', definition: 'White cell count' },
  { abbreviation: 'WFD', definition: 'Word finding difficulties' },
  { abbreviation: 'WFL', definition: 'Within functional limits' },
  { abbreviation: 'WNL', definition: 'Within normal limits' },
  { abbreviation: 'WPWS', definition: 'Wolff-Parkinson-White Syndrome' },
  { abbreviation: 'WZF', definition: 'Wheeled zimmer frame' }
]
